# JAVA project
language: java

jdk:
  - openjdk12
os:
  - linux

# no git logs
git:
  quiet: true

# using services
services:
  # - docker

jobs:
  include:
    - stage: build
      script: mvn clean install
    - stage: test
      script: mvn verify
    - stage: deploy
      script: mvn deploy
