# JAVA project
language: java

jdk:
  - openjdk8
  - openjdk9
os:
  - linux
  - osx

# no git logs
git:
  quiet: true

# using services
services:
  - docker

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  # - docker network create grid
  # - docker run -d -p 4444:4444 --net grid --name selenium-hub selenium/hub:3.141.59-radium
  # - docker run -d --net grid -e HUB_HOST=selenium-hub -v /dev/shm:/dev/shm selenium/node-chrome:3.141.59-radium
  # - docker run -d --net grid -e HUB_HOST=selenium-hub -v /dev/shm:/dev/shm selenium/node-firefox:3.141.59-radium

before_script:
  # - "export DISPLAY=:99.0"
  # - "sh -e /etc/init.d/xvfb start"
  # - sleep 3 # give xvfb some time to start

script:
  - "echo Hello World !"
